### ISSUE TITLE
ArrayIndexOutOfBoundsException in QualityCount.addValue

### ISSUE THREAD

**Issue by raser216** [s-andrews/FastQC#108]
@s-andrews 
Hello, 
I'm running FastQC v0.11.9 on a HPC cluster ( java version: 1.8.0_231-b11 ) for multiple samples at one time.  It sometimes throws this error message:
<img width="957" alt="1ce6b5df8cabf3ac0275b4d02d6b3892" src="https://user-images.githubusercontent.com/25073581/207319428-8434e502-4f91-4af5-abea-aa79c42c8f3f.png">

The command I use :
fastqc -j /usr/local/jdk1.8.0_231/bin/java -t 6 -a ./adapters.txt -o ./  ./${sample_name}_2.fq.gz  1>fastqc_do_2.stdout 2>fastqc_do_2.stderr && touch fastqc_do_2.SUCCESS

I gave 2GB memory for each fastq file and run several commands at one time. Is it a problem of multi-thread tasks?  Any suggestions to run FastQC for large number of datasets?

Thanks,
Raser

**Comment by s-andrews** [comment]
I had a look at this.  The crash you showed would only happen if you had a character in your quality string with a raw ASCII value of >150.  Assuming a standard PHRED33 encoding that would mean you'd have to have a PHRED score of > 117, which would seem to be absurdly high.  Certainly no sequencers should produce this high a value, so it's more likely that you've got some kind of corruption in your fastq file?

If you are able to share the raw fastq file with me I can take a look and see if I can see what's going on.

**Comment by raser216** [comment]
Thank you very much! I will check my fastq files if this error appears again. Unfortunately, the former files which throw this message were removed.
