### ISSUE TITLE
Raise 1000 tile limit or make it configurable for per-tile qualities calculations

### ISSUE THREAD

**Issue by rav-evax** [s-andrews/FastQC#112]
I have been running FastQC on some RNA samples.
FastQC does not calculate per-tile qualities due to more than 1000 tiles being present in the sample and so it thinks it is parsing the file wrongly. "Too many tiles (>1000) so giving up trying to do per-tile qualities since we're probably parsing the file wrongly"

However, I am fairly certain that it is parsing the file correctly, therefore, I would like to suggest to either up the 1000 tile limit or make it configurable.

https://github.com/s-andrews/FastQC/blob/bfde9d31aa94f29e9c58b6e91574a08e57335a4a/uk/ac/babraham/FastQC/Modules/PerTileQualityScores.java#L284

**Comment by s-andrews** [comment]
Thanks for reporting this.  Do you know which flowcell you saw the error on?  The largest we've seen in our data has been the S4 flowcell which seems to have 936 tiles, but that's still a little close to the limit so it probably makes sense to raise it anyway.

Illumina doesn't seem to have any obvious documentation on lane/swath/tile numbers on their flowcells so I can set a better number in an objective way.  I can try just taking it up to 2500 which will hopefully cover it.
