### ISSUE TITLE
New version is not available in Ubuntu

### ISSUE THREAD

**Issue by bounlu** [s-andrews/FastQC#116]
Please push the new version `v0.12.1` to Ubuntu:

https://manpages.ubuntu.com/manpages/jammy/man1/fastqc.1.html

**Comment by s-andrews** [comment]
We don't manage the version of FastQC distributed in Ubuntu or any of the linux distributions.  The timing of the updating of these packages is down to the debian / ubuntu maintainers who look after the package and it's up to them when the new version is pulled into their repositories.  Any requests for updates need to go to them directly as we have no influence on that I'm afraid.  You can always install the program directly from the binaries which we distribute and which will work on any of the linux distributions.

**Comment by tmancill** [comment]
Hi @bounlu .  I am a member of the [Debian Med](https://wiki.debian.org/DebianMed) packaging team, which maintains the [Debian packaging](https://tracker.debian.org/pkg/fastqc) of FastQC.  The package is being prepared and will be uploaded soon.

As Simon mentioned, you can report issues directly to [Debian](https://www.debian.org/Bugs/Reporting) and [Ubuntu](https://help.ubuntu.com/community/ReportingBugs) via their respective bug tracking systems.

**Comment by s-andrews** [comment]
> Hi @bounlu . I am a member of the [Debian Med](https://wiki.debian.org/DebianMed) packaging team, which maintains the [Debian packaging](https://tracker.debian.org/pkg/fastqc) of FastQC. The package is being prepared and will be uploaded soon.
> 
> As Simon mentioned, you can report issues directly to [Debian](https://www.debian.org/Bugs/Reporting) and [Ubuntu](https://help.ubuntu.com/community/ReportingBugs) via their respective bug tracking systems.

Can I just take this opportunity to thank you for the valuable work you do maintaining these packages.  It's very much appreciated.

**Comment by bounlu** [comment]
Thank you both @tmancill and @s-andrews for your quick response and valuable work. Much appreciated and can't wait to see the package ready on Ubuntu.
