### ISSUE TITLE
GPU Support available

### ISSUE THREAD

**Issue by MLServer3090** [s-andrews/FastQC#117]
Is there any plan for enabling GPU support for efficient QC for data? If not, are there any forks of FastQC available that provide GPU support?

**Comment by s-andrews** [comment]
No.  There is no plan to add GPU support to fastqc nor am I aware of any forks which do this.  I'm not sure that GPU would be all that helpful given the limiting steps in fastqc.  The slowest parts of the program are the reading and parsing of the fastq files and these aren't operations which would benefit from GPU capability.

If anyone fancies trying this I'd be very keen to see how it works out.
