### ISSUE TITLE
Latest version in Ubuntu

### ISSUE THREAD

**Issue by bounlu** [s-andrews/FastQC#121]
Ubuntu still has the old version 11.9.

Latest version 12.1 is not available in Ubuntu:
https://manpages.ubuntu.com/manpages/jammy/man1/fastqc.1.html

It would be handy to get the latest version via `apt install fastqc`.

I know the latest version can be installed by multiple other ways but `apt install` would be preferable in a Dockerfile rather than wget/conda etc.

**Comment by s-andrews** [comment]
We don't create the ubuntu packages for fastqc so can't help directly with this.

It looks like the new version is already in the upstream debian repository:

https://packages.debian.org/unstable/fastqc

..so it should make its way down to ubuntu in a future release.  Most linux distributions won't update a major version as a patch update so it's unlikely to be updated in existing releases so you'll need to install the new version manually if you want to use it there.
