### ISSUE TITLE
FastQC 0.12.1 showing useless line on run (application/gzip)

### ISSUE THREAD

**Issue by rarthur-eicc** [s-andrews/FastQC#127]
Hi, 

I've used FastQC for many years and am greatly appreciative of the program. Upon updating to 0.12.1, I am now getting a weird message to stdout or an output log while running on a Linux based server. This happens regardless of if this is a submitted job or just simply run from the CLI. It's minor, as things still work, but I am curious why it is occurring.

Upon running fastqc in an example with just one file, we see the following as it is working almost immediately upon starting:

`fastqc -q HH2K2DSX7_s1_1_IDT8_UDI_294.fastq.gz `
`
application/gzip
`

Why is it outputing "application/gzip" ? Reverting to 0.12.0 resolves this, but again, just curious.

**Comment by s-andrews** [comment]
Yeah, it was a debugging message from the fixes for the file type detection which didn't get removed before the release.  I've added a patch to remove it, but I'm not sure it's worth putting out a whole new release to fix this.  It doesn't do any harm and the fix will propagate into the next release.
