### ISSUE TITLE
Threads parameter description still specifies 250MB instead of 512MB

### ISSUE THREAD

**Issue by SergeWielhouwer** [s-andrews/FastQC#132]
Hi,

Thank you for developing FastQC.

I noticed that the threads description in the _--help_ for version 0.12.1 still specifies 250MB (per thread) instead of the newly set default of 512MB.

  -t --threads    Specifies the number of files which can be processed
                  simultaneously.  Each thread will be allocated **250MB** of
                  memory so you shouldn't run more threads than your
                  available memory will cope with, and not more than
                  6 threads on a 32 bit machine

```
if ($memory) {
	if ($memory < 100 || $memory > 10000) {
		die "Memory value $memory MB was outside the allowed range (100 - 10000)";
	}
}
else {
	$memory = 512;
}

if ($threads) {
	if ($threads < 1) {
		die "Number of threads must be a positive integer";
	}
	
	push @java_args ,"-Dfastqc.threads=$threads";
	my $used_memory = $memory * $threads;
	unshift @java_args,"-Xmx${used_memory}m";
}
else {
	unshift @java_args,"-Xmx${memory}m";
}
```

The code above seems to confirm that 512 MB is used per specified thread (if parameter is supplied).

Could you verify if this description should be updated?

Regards,

Serge

**Comment by s-andrews** [comment]
Yes, thank you - that value is wrong in the -t documentation.  I fixed it in --memory but not in --threads  I'll sort that out now...
