### ISSUE TITLE
Activate/deactivate modules dynamically upon command-line invokation

### ISSUE THREAD

**Issue by TBradley27** [s-andrews/FastQC#135]
Hello,

Firstly, thank you for the great tool

As discussed in the release notes for [v0.11.6](https://github.com/s-andrews/FaswitstQC/releases/tag/v0.11.6), not all modules are activated by default. In particular, the kmer module is not activated by default since v0.11.6

The current method for switching modules on or off is to edit the `Configuration` folder as [described](https://github.com/s-andrews/FastQC/releases/tag/v0.11.6)

One problem with this approach, is that it makes it difficult to dynamically switch modules on/off when using fastqc within a larger pipeline.

What would be helpful is if modules could be switched on/off at the command line using a command line option or flag

**Comment by s-andrews** [comment]
You can do this on the command line, but by the addition of a config file.  If you create a local copy of the ```limits.txt``` file then use the ```--limits``` option to pass the modified config file and this will be used over the global version installed with the program.  That way you can change the behaviour even if you don't have permission to edit the main configuration files.

**Comment by TBradley27** [comment]
My apologies for missing this. Thank you very much!
