### ISSUE TITLE
Accept input from STDIN

### ISSUE THREAD

**Issue by zamaudio** [s-andrews/FastQC#14]
Is it possible to stream data into FastQC from STDIN, such as in the following example:
```
cat *.fastq.gz | fastqc
```
This would enable multiple fastq files to get a single report?

I am using version 0.11.5, perhaps this is an old issue that has been resolved in later versions?

**Comment by s-andrews** [comment]
You can do this already, just use stdin as the filename. Not sure which version introduced it but it should be in the release notes if you search for stdin.

Let me know if you have any problems and I'll do a more complete reply - I'm doing this on a phone in a field, so apologies for the brevity!

**Comment by fgvieira** [comment]
But when it is specified like that, all filename information is lost (it shows up as `stdin`). Would it be possible to pass an ID to fastqc to use instead of the filename?

**Comment by plijnzaad** [comment]
I second this. Right now I have to jump through hoops to make the origin of the original fastq file visible in the HTML output by replacing each `stdin` in the html file with the name of the original file. A command line option to do this would be useful.

**Comment by s-andrews** [comment]
I think I might have missed the nuance of this.  Would it be enough that if you streamed a file to fastqc and passed a specific name for the output that the same name showed up in the summary for the report instead of 'stdin'?

**Comment by s-andrews** [comment]
I just went back to look at the code as this isn't a feature we actually use here -but you can do this already.

If you construct the command as:

```
zcat somefile.fq.gz | fastqc stdin:usethisname
```
Then the data will be read from stdin, but ```usethisname``` will be used to name the output files and written into the summary section of the report.

Does this do what you need?

**Comment by plijnzaad** [comment]
oh absolutely, that sounds very workable! Thanks,

Philip

**Comment by fgvieira** [comment]
Yes, that would be perfect!

**Comment by s-andrews** [comment]
> Yes, that would be perfect!

That functionality should be in the latest version already.

**Comment by fgvieira** [comment]
Ah yes, just needed to pipe uncompressed fastq.
thanks,

**Comment by zamaudio** [comment]
Closing as non-issue/fixed

**Comment by splaisan** [comment]
> I just went back to look at the code as this isn't a feature we actually use here -but you can do this already.
> 
> If you construct the command as:
> 
> ```
> zcat somefile.fq.gz | fastqc stdin:usethisname
> ```
> 
> Then the data will be read from stdin, but `usethisname` will be used to name the output files and written into the summary section of the report.
> 
> Does this do what you need?

this would deserve be exposed in the manpage, it is very useful for platforms (eg MGI) which output multiple fastq for a single library and repacking them takes considerable amounts of time

**Comment by Mar111tiN** [comment]
I second splaisan's comment. The naming feature from stdin is very handy and should definitely appear in the man-page /help. Would have saved me like 3 hours :-)
Great tool!

**Comment by fabio-marcelo** [comment]
Hi everyone! I've used `zcat somefile.fq.gz | fastqc stdin:usethisname` and the output files carry `stdin:` in the file names. I mean, the output is `stdin:sample1.fq.gz`. Is there a way to avoid that and get just `sampel1.fq.gz`?

**Comment by s-andrews** [comment]
Which version of fastqc are you using?  I just tried this with the latest version and didn't see this behaviour:

```
zcat example.fq.gz | fastqc stdin:example.fq.gz
```

..gave me:

```
-rw-rw-r--  1 andrewss bioinf            380876 Apr 17 15:38  example_fastqc.zip
-rw-rw-r--  1 andrewss bioinf            583092 Apr 17 15:38  example_fastqc.html
```

..and the file just has the name, not the prefix:

![image](https://github.com/s-andrews/FastQC/assets/8157923/66b8b65a-601e-498e-b7b7-9b23aa9bb42e)

**Comment by fabio-marcelo** [comment]
I've used the container `quay.io/biocontainers/fastqc:0.11.9--0`.

**Comment by s-andrews** [comment]
That's a pretty old version now.  The latest version has fixed this already so there's nothing to change here.

There seems to be a 0.12.1 biocontainer available https://biocontainers.pro/tools/fastqc which should fix this for you.

**Comment by fabio-marcelo** [comment]
Thanks, @s-andrews .
