### ISSUE TITLE
Unable to open Fastqc

### ISSUE THREAD

**Issue by karthi-ntu** [s-andrews/FastQC#143]
Hello Andrews,
I have downloaded the latest version of fastqc windows version as zip file and extracted it. I am able to access fastqc from git bash. But unable to open Fastqc in cmd.

1) I have added path to variables. 
2) I accessed fastqc directory in cmd but still can't run "fastqc --help" command.
3) I tried running cmd as administrator
4) I could not find fastqc.exe file in the unzipped folder. But can find linux executable file.
5) Six months back I used fastqc in mac without any issue.

Thanks.

**Comment by s-andrews** [comment]
Windows doesn't have the same command line interface that you get in linux.  The nearest we have is the ```run_fastqc.bat``` file which you can use instead to launch the program.

If you want full command line options like you get on mac/linux then you'd need to install something like [ActivePerl ](https://www.activestate.com/products/perl/) on your machine and then run:

```perl c:/whichever/folder/FastQC/fastqc --help```

..which I think will work the same as on linux.

**Comment by karthi-ntu** [comment]
Thanks for letting me know. It is working now.
