### ISSUE TITLE
`FastQC` still showed "GGGGGGG" as over-represented sequence with "No Hit" Source even after `--trim_poly_g` in `fastp`.

### ISSUE THREAD

**Issue by denvercal1234GitHub** [s-andrews/FastQC#146]
Hi there, 

Thanks for the tool. 

I have some paired-end bulkRNAseq. I ran `fastp` as below with `--trim_poly_g ` but in the `FASTQC` report for a sample, there was still shown issue with over-represented sequence of GGGGGGGG... in the R2 read. with "No Hits" in the Source. 

Would you mind giving me some pointers to address this issue? 

Thank you for your help. 

![Screenshot 2024-12-14 at 18 12 33](https://github.com/user-attachments/assets/0c14d68a-f1a9-4247-b705-0838137774b1)

![Screenshot 2024-12-14 at 18 12 50](https://github.com/user-attachments/assets/5988823d-a41f-47f4-b506-448eb22e0b53)

![Screenshot 2024-12-14 at 18 09 39](https://github.com/user-attachments/assets/310b0d67-619f-4a83-87c0-a43159cc0e44)

```
fastp \
    --adapter_fasta /ceph/project/borrowlab/qnguyen/RAW_bulkRNASeq_TMNCTFHTREGCD8_QNN2024Aug19/X204SC24072759-Z01-F001_02/01.RawData/for_Trimming.fasta \
    --adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA \
    --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT \
    --qualified_quality_phred 5 \
    --unqualified_percent_limit 50 \
    --n_base_limit 15 \
    --overlap_len_require 30 \
    --overlap_diff_limit 1 \
    --overlap_diff_percent_limit 10 \
    --length_required 150 \
    --length_limit 150 \
    --trim_poly_g \
    -i "$file" \
    -I "$r2_file" \
    -o "$output_r1" \
    -O "$output_r2"
```

Referenced at https://github.com/OpenGene/fastp/issues/589

**Comment by s-andrews** [comment]
The overrepresented sequences in FastQC just search (by default) the first 50bp of each sequence.  You have 150bp sequences.

When you trim polyG it will trim from the 3' end back.

The most likely explanation, assuming you've run fastp correctly, is that you have sequences which start with polyG but move into something else before the end of their 150bp length.  If that's the case then neither program is doing anything wrong here.
