### ISSUE TITLE
parameters and effects

### ISSUE THREAD

**Issue by bernt-matthias** [s-andrews/FastQC#18]
Dear @s-andrews just did some experiments with some other parameters. Some don't show an effect on the results for [data set](https://raw.githubusercontent.com/galaxyproject/tools-iuc/ea0ba45442a642c16f8de2e875955e18b355b569/tools/fastqc/test-data/1000trimmed.fastq) used for testing the Galaxy tool. For at least two of them I would expect an effect: 

- --kmer 3 definitely should show some over represented sequences
- -adapters file should add columns to the adapter section, but only fastqc default adapaters show up
- same for contamination (but this could be a problem of the test set)

for the latter [this file](https://raw.githubusercontent.com/galaxyproject/tools-iuc/master/tools/fastqc/test-data/fastqc_contaminants.txt) was used .

**Comment by s-andrews** [comment]
I started with the easy one - the adapters option.  It all seems to work fine when I tried it here:

```
$ cat adapter_list.txt
Illumina Universal Adapter                                      AGATCGGAAGAG
Illumina Small RNA 3' Adapter                           TGGAATTCTCGG
Illumina Small RNA 5' Adapter                           GATCGTCGGACT
Nextera Transposase Sequence                            CTGTCTCTTATA
SOLID Small RNA Adapter                                         CGCCTTGGCCGT
Test adapter                                                                                    AAAAAAAAAAAA

$ fastqc --quiet --adapter adapter_list.txt test.fastq

$ unzip test_fastqc.zip
Archive:  test_fastqc.zip
   creating: test_fastqc/
   creating: test_fastqc/Icons/
   creating: test_fastqc/Images/
  inflating: test_fastqc/Icons/fastqc_icon.png
  inflating: test_fastqc/Icons/warning.png
  inflating: test_fastqc/Icons/error.png
  inflating: test_fastqc/Icons/tick.png
  inflating: test_fastqc/summary.txt
  inflating: test_fastqc/Images/per_base_quality.png
  inflating: test_fastqc/Images/per_tile_quality.png
  inflating: test_fastqc/Images/per_sequence_quality.png
  inflating: test_fastqc/Images/per_base_sequence_content.png
  inflating: test_fastqc/Images/per_sequence_gc_content.png
  inflating: test_fastqc/Images/per_base_n_content.png
  inflating: test_fastqc/Images/sequence_length_distribution.png
  inflating: test_fastqc/Images/duplication_levels.png
  inflating: test_fastqc/Images/adapter_content.png
  inflating: test_fastqc/fastqc_report.html
  inflating: test_fastqc/fastqc_data.txt
  inflating: test_fastqc/fastqc.fo

$ grep Test test_fastqc/fastqc_data.txt
#Position       Illumina Universal Adapter      Illumina Small RNA 3' Adapter   Illumina Small RNA 5' Adapter   Nextera Transposase SequenceSOLID Small RNA Adapter Test adapter

```

The test adapter also shows up in the HTML report graph.

**Comment by s-andrews** [comment]
For the Kmers - the Kmer module is disabled by default (as it's prone to over-predict and is difficult to interpret) so you'd need to adjust the limits.txt file to re-enable it if you wanted it to actually run.

**Comment by s-andrews** [comment]
For the adapter additions, these will only do anything if the program finds any over-represented sequences (single sequences making up >0.1% of the library).  Then the added sequence would need to be a good match to a previously unidentifed overrepresented sequence.

**Comment by bernt-matthias** [comment]
Hi @s-andrews. Thanks for you comments. I got  --kmer and --adapters running. I'm still struggling with an idea for a test for the  --contaminants file that shows an effect on the output.

**Comment by s-andrews** [comment]
You'd need to find out make a fastq fire which has an over represented sequence which doesn't match any of the existing contaminants shipped with fastqc. You could just append an identical sequence on the end of an existing file a bunch of times. 

If you then add this sequence to a custom contaminants file you should see that it changes in the output from being unannotated to having your custom annotation out on it.
