### ISSUE TITLE
Duplication estimation with paired-end reads

### ISSUE THREAD

**Issue by thbtmntgn** [s-andrews/FastQC#20]
Hi Simon,

FastQC is showing me that I have ~20% duplicate reads paired-end samples files but when using tools to discard duplicate reads this percentage is actually way lower (<5%).

After looking at FastQC documentation, my idea is that such results can be explained by the fact that FastQC is processing R1 and R2 reads separately and not processing them as a pair. Is it correct?

Thanks,
Thibaut

**Comment by s-andrews** [comment]
That's one reason, also if you have long reads then fastqc only matches based on the first 50bp so if you have reads which diverge after this point then they will be considered to be duplicates by the program.
