### ISSUE TITLE
BAM file error: "ID line didn't start with '@'"

### ISSUE THREAD

**Issue by slzarate** [s-andrews/FastQC#27]
I am running into this issue when running FASTQC with a BAM file input: `uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'`

When I run `samtools view -H` on the BAM file I am using, the first few lines start with this:

```
@HD     VN:1.3  SO:coordinate
@SQ     SN:1    LN:249250621
@SQ     SN:2    LN:243199373
```

Could you provide some insight into why I am running into this error?

**Comment by bny6613** [comment]
Based on the error message, seems like your file doesn't have .bam extension and the tool tries to read it as .fastq (which is default).
