### ISSUE TITLE
Fatal Error in JRE

### ISSUE THREAD

**Issue by fullama** [s-andrews/FastQC#29]
Since updating  from 11.5 to 11.8 we are now seeing fastqc occasionally fail. 
The following error is reported:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007fc6f89dc69b, pid=2426, tid=140492580919040
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libfontconfig.so.1+0x869b]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /logs/run/1/hs_err_pid2426.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
I would have thought that it was something wrong with our java or something like that but it has only started happening since we went from fastqc 11.5 to 11.8. I tried anyway updating JRE to the version shown above but the error still occurs.

I cannot see any reason it is failing, but it is happening on something like 1 in every 1000 fastq files. I can't reproduce it either as when I run the exact same command that was originally used on those runs that failed, fastqc finishes without any errors. 1 in every 1000 doesn't seem like a lot but it gets frustrating having to go and manually rerun fastq every day for the select few samples that fail.

Any ideas where to go with this? would the full error report be of any use? I know I haven't given a lot of information here but I don't have a lot to go on - any help would be appreciated.

**Comment by bny6613** [comment]
Make sure that your /tmp has enough space. There is a known issue when java crashes with sigbus when /tmp is full. Fastqc uses tmp folder during report generation. You also can specify it with --dir parameter.
