### ISSUE TITLE
invalid jarfile

### ISSUE THREAD

**Issue by ReginaHanlon** [s-andrews/FastQC#31]
I have downloaded from the site listed and get a corrupt jarfile error.  Can you help me fix this? Thx
https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip

Reginas-MacBook-Pro-2:programs reginahanlon$ java -jar /Users/reginahanlon/programs/FastQC/fastqc -v
Error: Invalid or corrupt jarfile /Users/reginahanlon/programs/FastQC/fastqc

I have downloaded Trimmomatic and it shows the following when I ask -version.
Reginas-MacBook-Pro-2:Trimmomatic-0.38 reginahanlon$ java -jar /Users/reginahanlon/programs/Trimmomatic-0.38/trimmomatic-0.38.jar -version
0.38

**Comment by bny6613** [comment]
fastqc is a shell script (not a jar file). You need to run it directly ```./fastqc -v```

**Comment by ReginaHanlon** [comment]
Thanks for clarifying, I thought there was more I could do than the shell script and that works.
