### ISSUE TITLE
Hang with version 0.11.8, but not with version 0.11.5

### ISSUE THREAD

**Issue by zamaudio** [s-andrews/FastQC#35]
We process quite a bit of data through fastqc and recently discovered a valid fastq file that seems to hang for hours on version 0.11.8 but when the same file is run through version 0.11.5, it completes in a few seconds.

Once I have permission to share the file I will upload it here.

**Comment by zamaudio** [comment]
I tried running it on a few different machines and got this error after some time:
```
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at uk.ac.babraham.FastQC.Utilities.QualityCount.<init>(QualityCount.java:33)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:281)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zamaudio** [comment]
It turns out that FastQC was running out of memory with default of 250M, when I increased it to 1G the file processed in a few seconds.  I can confirm that running `fastqc --threads 4` also fixed the problem.

**Comment by s-andrews** [comment]
Thanks for the update.  Was this a file with unusually long read lengths or was in some other way unusual?  This kind of memory exhaustion shouldn't happen on normal looking illumina stye data.

**Comment by zamaudio** [comment]
It was a negative control sample, so probably random noise.
