### ISSUE TITLE
Library is in the JAR

### ISSUE THREAD

**Issue by haileeshen** [s-andrews/FastQC#36]
Hi, I find there a 3 so embedded in the Jar, and I read the elf header of the .so files （libjhdf5.so,libnativedata.so,libunix.so,）, they all are x.86 format, but my server is  Aarch64 (ARM v8A) based, so can you share the  source code of the libraries with me, the I can regenerate  them use arm GCC?
Also it's fine if you can share the download URL of the source code.
Thanks a lot.
Haile.

**Comment by s-andrews** [comment]
I think these are probably part of the hdf5 library which we ship along with FastQC so we can read Fast5 files.  These originally come from:

https://wiki-bsse.ethz.ch/display/JHDF5/Download+Page

It's possible that newer versions of the library support more architectures, so it might be possible to do a drop in replacement for the current library to support other platforms.  Other than that you'd need to re-compile the native parts of the library and replace the standard version we've copied.  All of the source should be available, but I don't know whether you'd also need to modify the wrapper script which figures out which binaries to use.

I should note that all of this is only necessary for analysing Fast5 files (generally containing nanopore data).  FastQ / BAM / SAM do not require any code from this library.

**Comment by haileeshen** [comment]
Hello Simon,
Thanks for your information. 
Clear for me,  seems I should contact with CISD (now is ETH SIS) to request the feature. 
Also this is import for me, because current stage fast 5 format is not in our scope, so we can use fastQC on my Aarch64 server, happy...
Thanks again and best Regards,
Haile.
