### ISSUE TITLE
Error: Unrecognized sequence format despite file being a fastq file

### ISSUE THREAD

**Issue by TaylorLeigB** [s-andrews/FastQC#50]
Hello, 

For some reason when I try to use FastQC to check the quality of my sequence data after trimming  off illumina adapters using bbduk, FastQC will not recognize my fastq files as an acceptable format. I used this script when trimming my files in bbduk: #!/bin/bash

"for libraryfile in ~/Desktop/Taylor/Demultiplexed_reads/SUL03_demultiplexed_reads/*R1.fastq; 
  do 
	libraryfilename=$(basename $libraryfile) 
	LIBRARY=${libraryfilename%_R1.fastq.gz} 
	echo "now processing ${libraryfile}" 
	bbduk.sh in=${libraryfile} out=${libraryfilename}_passed.fastq \
		outm=${libraryfilename}_failed.fastq ref=adapters \ 
		 
lliteral=CGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT,GCATGTCCCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT,TGCAACGCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT,ATGCATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT,CATGCCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT 
		k=23 ktrim=r mink=11 hdist=1 rcomp=t stats=statsSUL1.txt
done"
 and here is the 8 lines in one of the data files that FastQC will not accept:

@HWI-ST766:54:D27FAACXX:3:1101:5933:3469 1:N:0:
GCCCTAAGCTGGATTTCTAGGGGTACCTCTGAGTGCATGGAGTGGTCGCCCGGAGTTTGGGGGAGAATGCAACCCAGTTTTCGTATCGAAATTA
+
DDFHFDHBGHIIDIGIIGIGFIG8?CFHGIFBF?B9DG@B<B9?D?DAFGGEE8B?@BBB>CBBBBBACCCACBCCBA@DCCCBCCBB<?8ACC
@HWI-ST766:54:D27FAACXX:3:1101:6149:3374 1:N:0:
GTCCAGAAAGTTATTTTGATACACCCCTGCCCCCCCCCCCCCCCTTTTCTCCCCCCTCGCCTTGGACTCCCCTCTTTGTGGTGCCTCGCGCGTT
+
FFGHHHHJJIJJGJJIJHHIHIGHIBH??DGHIJJIJFDD?#####################################################

Has anyone encountered this problem before? If not, any advice is greatly appreciated. 

Thanks!
Taylor

**Comment by TaylorLeigB** [comment]
Here is the code I am using:

FastQC -o /Users/jasonaddison/Desktop/Taylor/FastQCoutput  -f /Users/jasonaddison/Desktop/Taylor/testSU03.fastq
Unrecognised sequence format '/Users/jasonaddison/Desktop/Taylor/testSU03.fastq', acceptable formats are bam,sam,bam_mapped,sam_mapped and fastq

**Comment by s-andrews** [comment]
The ```-f``` flag doesn't do what you think it does.  Files to process just go on the end of the command.  The ```-f``` option forces FastQC to override its normal format detection and treat a file as a specific format.

If you just run:

```
FastQC -o /Users/jasonaddison/Desktop/Taylor/FastQCoutput /Users/jasonaddison/Desktop/Taylor/testSU03.fastq
```

..it should work.

**Comment by TaylorLeigB** [comment]
Thank you so much aha. I can't believe I didn't figure this out soon... Cheers!!
