### ISSUE TITLE
How to cite FastQC?

### ISSUE THREAD

**Issue by Midnighter** [s-andrews/FastQC#51]
I could not find any information on how to cite FastQC neither on the website https://www.bioinformatics.babraham.ac.uk/projects/fastqc/ nor here. Also searching for a publication did not turn up anything. Do you have any associated publication?

**Comment by s-andrews** [comment]
There is no paper for FastQC.  Citing the project URL as you suggested is what we'd recommend.

**Comment by Midnighter** [comment]
Okay, thanks!
