### ISSUE TITLE
Mean of Phred score

### ISSUE THREAD

**Issue by moritzschaefer** [s-andrews/FastQC#56]
I was just stumbling upon this issue [NanoPlot had a few years ago](https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/) and wondered how FastQC is dealing with this issue: 

The Phred score is the [logarithmic value of probability](https://en.wikipedia.org/wiki/Phred_quality_score) so taking the mean of this score does not lead to a useful representation of the data. Rather (as the blog post of NanoPlot above suggests) to get the expected value one would have to first convert the Phred scores to probabilities before taking the mean. 

I did not have a look into the code, but the results of my FastQC runs suggest that it is not implemented the way NanoPlot suggests it. I think it's an easy fix if you're familiar with the code base, however I could also help out and file a PR some time in the future.

Affected plots:
- Per base sequence quality
- Per sequence quality scores

**Comment by s-andrews** [comment]
Thanks for getting in touch about this.  I think I disagree with the conclusion (but not the maths) from that original article, and that the way we are performing the analysis here is more representative of the data.

The aim with the per base / per sequence plots isn't really to calculate a meaningful probability value, but to provide useful information about the overall quality of the base / sequence.  Raw base call probabilities aren't going to be normally distributed in the first place, so the mean isn't really a great summary of the data, but phred scores do at least form a distribution with a reasonably symmetric central tendency (as you can see from the per base quality distribution plot) so the mean phred is actually a value which varies in a meaningful way.  The aim of those plots is to be able to see shifts in trends, and for the per sequence plot to be able to see if you have multiple distribtions or if everything is similarly good / bad, and the effect from real runs is that these trends are indeed evident when things go wrong so the current handing of the data acheives the intended effect.

If you'd like to try to reimplement a different summarisation method then I'd be more than happy to help you work through the code in a fork to get this working - it should be relatively straight forward.  I think I'd need to see pretty convincing results from real dataset which showed that the different summarisation produced clearer illustrations of the problems in the data before I'd consider pulling this into a new release though.

**Comment by moritzschaefer** [comment]
Hey @s-andrews, 

thanks for ellaborating on this one. I see your point in this matter and also realize that the usefulness of such a change would need to be proven before changing the plots of such a widely used tool!

I was anyways surprised to not have seen any GitHub issue here bringing up this topic, so maybe this small conversation (i.e. your response) can give some insights in case someone is stumbling over this topic in the future.
