### ISSUE TITLE
How to display total bases in FASTQC reports?

### ISSUE THREAD

**Issue by KTbiotech** [s-andrews/FastQC#58]

**Comment by s-andrews** [comment]
Sorry, but I don't think this value is directly reported.  We give the total number of reads and the distribution of insert sizes, but these aren't recorded exactly (they're split into categories), so you can't calculate a completely accurate value from them.

This would actually be super easy to add so I'll put this into the geneal stats section.

**Comment by s-andrews** [comment]
There's a new snapshot with this function added at:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/FastQC_v0.11.10.devel.zip

This will be included in the next release.

**Comment by KTbiotech** [comment]
Thank you.
