### ISSUE TITLE
(.:19828): Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by woaishiye** [s-andrews/FastQC#59]
Dear author:
      i installed fastqc_v0.11.9 and when i run it with my data, i got the following mistake, i can realize that maybe this is a problem of my linux sever, but i don't know how to solve it, please help me!!

Started analysis of raw_read_1.fq.gz
Approx 5% complete for raw_read_1.fq.gz
Approx 10% complete for raw_read_1.fq.gz
Approx 15% complete for raw_read_1.fq.gz
Approx 20% complete for raw_read_1.fq.gz
Approx 25% complete for raw_read_1.fq.gz
Approx 30% complete for raw_read_1.fq.gz
Approx 35% complete for raw_read_1.fq.gz
Approx 40% complete for raw_read_1.fq.gz
Approx 45% complete for raw_read_1.fq.gz
Approx 50% complete for raw_read_1.fq.gz
Approx 55% complete for raw_read_1.fq.gz
Approx 60% complete for raw_read_1.fq.gz
Approx 65% complete for raw_read_1.fq.gz
Approx 70% complete for raw_read_1.fq.gz
Approx 75% complete for raw_read_1.fq.gz
Approx 80% complete for raw_read_1.fq.gz
Approx 85% complete for raw_read_1.fq.gz
Approx 90% complete for raw_read_1.fq.gz
Approx 95% complete for raw_read_1.fq.gz

(.:19828): Gtk-WARNING **: cannot open display:

**Comment by s-andrews** [comment]
I'm not really sure what would trigger this.  When you run fastqc in non-interactive mode we launch it with the java.awt.headless flag set so it shouldn't interact with your GTK session. It would only be if the JRE itself linked to that that something could potentially be problematic.

Something I've seen in other software projects is that the default linux theme for java apps is pretty buggy and has triggered warnings from the OS (but not errors or crashes).  I could try disabling that for fastqc too in case this is a more extreme version of that issue?
