### ISSUE TITLE
some of failures of FastQC report

### ISSUE THREAD

**Issue by lovelymaoqin** [s-andrews/FastQC#60]
I am very new to RNAseq and fastqc. I got the report which shows some failures as below. And also I attached the failure pictures, would you give me some suggestions? Thanks in advance!!

![adapter_content (1)](https://user-images.githubusercontent.com/62307133/94631934-35bf9f80-0297-11eb-9eb7-ae20b28919b1.png)
![per_base_n_content (1)](https://user-images.githubusercontent.com/62307133/94631963-4cfe8d00-0297-11eb-8009-88eac3ec14f3.png)
![per_sequence_gc_content](https://user-images.githubusercontent.com/62307133/94632038-92bb5580-0297-11eb-91eb-96fd8a476770.png)
![per_sequence_quality (2)](https://user-images.githubusercontent.com/62307133/94632057-9c44bd80-0297-11eb-867f-6b131be10f75.png)
![per_tile_quality (1)](https://user-images.githubusercontent.com/62307133/94632061-a1a20800-0297-11eb-8ef5-0f43de57406c.png)

**Comment by s-andrews** [comment]
Only some of those look like they would trigger failures.

The adapter one shows you've got a high proportion of reads with adapters, but it looks like this is a small RNA library, so it's completely expected that you'd get short inserts, and therefore high adapter content.

The GC distribution is not smooth, showing a non-diverse population in your library, but again this could be the nature of your small RNAs where a small subpopulation dominates the library.  Can't be conclusive about this one but it's not something which is a big red flag in this context.

The per tile quality does have a couple of glitches in it, but they're for inidividual tiles for a single cycle.  Possibly just a transient bubble going through the flowcell.  Given the small and non-lasting impact of these I wouldn't worry about them.
