### ISSUE TITLE
Installation issue of fastqc

### ISSUE THREAD

**Issue by kiraxiaozhi** [s-andrews/FastQC#63]
Hi, I am trying to install fastqc in macOS Bigsur. 
I have Downloaded and expanded fastqc_v0.11.9.zip and Run the codes below
 ```chmod +x fastqc```
```sudo ln -s /Absolute/path/to/fastqc /usr/local/bin/fastqc```

after that, I tried ```fastqc --help```, which gives me command not found.

Am I missing something?

**Comment by s-andrews** [comment]
Where it says ```/Absolute/path/to/fastqc``` that isn't meant to be taken literally but replaced with the actual location where you unzipped the FastQC install, so on my machine it would be something like:

```ln -s /home/andrewss/FastQC/fastc /usr/local/bin/fastqc```

You'll need to ammend that command to use the folder you actually have the program in.

**Comment by kiraxiaozhi** [comment]
Hi Andrew. After I run: "cd /Users/qchen/Downloads" where I have the unzipped files,  I run the "chmod +x fastqc" and "sudo ln -s /Users/qchen/Downloads /usr/local/bin/fastqc". It asks my password, but then shows: " ln: /usr/local/bin/fastqc: File exists ". Do I need to delete the existed file? What is the next step for it?
Thank you!

**Comment by s-andrews** [comment]
Because you have an earlier failed attempt in there you need to do:

```sudo ln -sf /Users/qchen/Downloads /usr/local/bin/fastqc```

to force it to replace the existing link
