### ISSUE TITLE
Only the first 100,000 reads analyzed?

### ISSUE THREAD

**Issue by ssk2020311** [s-andrews/FastQC#64]
Is it true that FastQC only analyzes the first 100,000 reads? Is this true of all versions of the tool? Also is this true for all the metrics (adapter content, quality of reads, etc) that are reported.

**Comment by s-andrews** [comment]
No, not really.  It's only true for the modules which deal with duplication (so duplication and overrepresented sequences), where we have to store the sequences which have been seen, and if you don't put a limit on that you end up having to (potentially) store every sequence in the file, which goes badly when you have a big diverse dataset.

Even then, we still look at all of the data - we just take the first 100,000 **different** sequences and track them through the entire dataset and then extrapolate to get the overall expected duplication figures for the whole dataset.

Modules like the quality and composition use all reads.

**Comment by smb20200615** [comment]
Thank you so much for the clarification. Also am I correct in that only a limited set of adapters will be searched but than one can  provide additional adapter sequences that will be searched against the library?

**Comment by s-andrews** [comment]
Yes, you can add new sequences to Configuration/contaminant_list.txt if you have more sequences you want to search against.
