### ISSUE TITLE
how to solved key called ge_sequence?

### ISSUE THREAD

**Issue by modarzi** [s-andrews/FastQC#69]
Dear @s-andrews and others I would like to assess the quality of my Fastq files with the FastQC tool. my data is control access in dbGaP. I downloaded it through the dbGaP protocol. now I run fastqc  for gaining quality of that fastq files but I got the below error:

`No key called gc_sequence:ignore in the config data`

I see this [issue](https://github.com/s-andrews/FastQC/issues/5)  but In my FastQC path (/usr/bin/fastqc) I couldn't find any limit.txt or Configure file. My Linux is Ubuntu (16.04.7).
I appreciate it if you share your comment with me.
Best Regards,

**Comment by s-andrews** [comment]
The problem in #5 was that the linux distribution had re-packaged FastQC, but hadn't done it correctly and their version was broken.  Since this is not something we did or have any control over there's nothing I can do to directly fix that.  The best thing to do would be to just download and install FastQC from the original project page https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc and follow the install instructions to use that version instead.  That should get things working for you.

Let me know if you have any problems getting this to work.

**Comment by tmancill** [comment]
This behavior sounds very much like the behavior introduced in the Debian packaging of FastQC, specifically, [this patch](https://salsa.debian.org/med-team/fastqc/-/blob/master/debian/patches/set_configuration_path.patch), which moves the configuration files off of the classpath and into `/etc/fastqc/Configuration/`.

I can appreciate that having these files in `/etc/` isn't going to be ideal for many use cases.  What do folks think about updating the Debian patch to check in `$HOME/fastqc/Configuration/` (or similar) and then fall back to `/etc/fastqc/Configuration/` if there isn't a user-specific configuration present?

**Comment by s-andrews** [comment]
To be honest, from what we've seen very few people ever actually modify the stock configuration files, so customised files are a somewhat niche use case.  There's also an option on the command line to specify custom adapter or contaminant files already.

If you want to add a default search in ```~/fastqc/Configuration``` which falls back to ```/etc/``` then that's great, but as long as the basic ```/etc/``` configuration works then that will work for pretty much everyone on its own.

**Comment by modarzi** [comment]
> This behavior sounds very much like the behavior introduced in the Debian packaging of FastQC, specifically, [this patch](https://salsa.debian.org/med-team/fastqc/-/blob/master/debian/patches/set_configuration_path.patch), which moves the configuration files off of the classpath and into `/etc/fastqc/Configuration/`.
> 
> I can appreciate that having these files in `/etc/` isn't going to be ideal for many use cases. What do folks think about updating the Debian patch to check in `$HOME/fastqc/Configuration/` (or similar) and then fall back to `/etc/fastqc/Configuration/` if there isn't a user-specific configuration present?

Thanks for your response. I need to find Configuration file because @s-andrews  wrote in the [issue](https://github.com/s-andrews/FastQC/issues/5) below response:

```
I think something must have happened to your limits.txt file which is in the Configuration directory of your FastQC installation (or possibly a different location if you passed the --limits option when you ran FastQC).

In that file there should be a line which looks like:
gc_sequence ignore 0

..and that line must either be missing, or the formatting has been messed up in your copy of FastQC.
```

**Comment by s-andrews** [comment]
I think that the issue is that the Debian package moved these files somewhere under ```/etc``` but didn't correctly update the FastQC code to look for them in that location.  The immediate fixes to this for an individual machine would be:

1. Install a copy of FastQC from the project page and use that since it will have all the files in the expected location
2. Find where under /etc/the configuration file is and manually supply that location using the ```--limits``` option.  You might also need to pass ```--adapters``` and ```--contaminants``` if those files can't be found too.

**Comment by tmancill** [comment]
> I think that the issue is that the Debian package moved these files somewhere under `/etc` but didn't correctly update the FastQC code to look for them in that location. The immediate fixes to this for an individual machine would be:
> 
> 1. Install a copy of FastQC from the project page and use that since it will have all the files in the expected location
> 2. Find where under /etc/the configuration file is and manually supply that location using the `--limits` option.  You might also need to pass `--adapters` and `--contaminants` if those files can't be found too.

Apologies for the delay.  I can speak to the location of the files in Debian package.  The files are found in `/etc/fastqc/Configuration/` and the sources [have been patched](https://salsa.debian.org/med-team/fastqc/-/blob/master/debian/patches/set_configuration_path.patch) to read them there.  And the key exists in the file: 

```
$ ls -1 /etc/fastqc/Configuration
adapter_list.txt
contaminant_list.txt
limits.txt

$ grep gc_sequence /etc/fastqc/Configuration/limits.txt                               
gc_sequence	ignore 	0
gc_sequence	warn	15
gc_sequence	error	30
```

I am not able to reproduce the bug in the current Debian version.  If there is a Debian-specific issue, the [Debian Bug Tracking System](https://www.debian.org/Bugs/Reporting) is obviously the right forum, but I will keep an eye out for issues reported here.

**Comment by modarzi** [comment]
> The problem in #5 was that the linux distribution had re-packaged FastQC, but hadn't done it correctly and their version was broken. Since this is not something we did or have any control over there's nothing I can do to directly fix that. The best thing to do would be to just download and install FastQC from the original project page https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc and follow the install instructions to use that version instead. That should get things working for you.
> 
> Let me know if you have any problems getting this to work.

Dear @s-andrews, I downloaded FastQC from your recommended address and run it for my RNA-seq samples. I see again that FastQC progress 95% of my file but it cant complete the QC process and I get the below error:
```
Exception in thread "Thread-1" java.lang.IllegalArgumentException: No key called gc_sequence:ignore in the config data
    at uk.ac.babraham.FastQC.Modules.ModuleConfig.getParam(ModuleConfig.java:148)
    at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.ignoreInReport(PerSequenceGCContent.java:57)
    at uk.ac.babraham.FastQC.Results.ResultsPanel.analysisComplete(ResultsPanel.java:117)
    at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
    at java.lang.Thread.run(Thread.java:748)
```
I appreciate it if you share your comment with me.

**Comment by s-andrews** [comment]
Are you sure that you're using the newly downloaded version?  I'd be very suspicious that you're still using the broken OS version.

What is the command which you're using to launch fastqc?  If you're not giving an explicit path to fastqc (eg ```/home/you/FastQC/fastqc``` then what do you get if you run:

```which fastqc``` in a terminal?

That will tell you which version is being used by default.

**Comment by modarzi** [comment]
> Are you sure that you're using the newly downloaded version? I'd be very suspicious that you're still using the broken OS version.
> 
> What is the command which you're using to launch fastqc? If you're not giving an explicit path to fastqc (eg `/home/you/FastQC/fastqc` then what do you get if you run:
> 
> `which fastqc` in a terminal?
> 
> That will tell you which version is being used by default.

I run fastqc command in every directory in my Linux and see a window relate to Fastqc tool. In the window, I see the version of it as 0.11.4. 

also, I run the below command:

`which fastqc`

I see below message:

`usr/bin/fastqc`

I appreciate it if you share your comment with me.

**Comment by tmancill** [comment]
Hi @modarzi .  Thank you for sharing the version.  0.11.4 was not part of a Debian stable release, but I was able to find it on the Ubuntu package page:  https://launchpad.net/ubuntu/+source/fastqc/0.11.4+dfsg-3

It is just over 5 years old and almost certainly lacks the updates we have been discussing:

```
fastqc (0.11.4+dfsg-3) unstable; urgency=medium

  * Build-Depends: libhtsjdk-java | libsam-java and try to enable
    htsjdk.jar in Build system

 -- Andreas Tille <tille@debian.org>  Thu, 14 Jan 2016 13:50:56 +0100
```

I suggest you upgrade.  If you would like to continue to using the Debian/Ubuntu packaging, you can try installing either the current [Ubuntu](https://launchpad.net/ubuntu/+source/fastqc/0.11.9+dfsg-4/+build/20177745/+files/fastqc_0.11.9+dfsg-4_all.deb) or [Debian](http://ftp.debian.org/debian/pool/main/f/fastqc/fastqc_0.11.9+dfsg-4_all.deb)  .deb.  Download the .deb and install it with `sudo dpkg --install fastqc_0.11.9+dfsg-4_all.deb`.

As an alternative (and very likely a quicker path to resolution on an older system), use the instructions here http://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc to download and install as @s-andrews has suggested.

**Comment by modarzi** [comment]
> Hi @modarzi . Thank you for sharing the version. 0.11.4 was not part of a Debian stable release, but I was able to find it on the Ubuntu package page: https://launchpad.net/ubuntu/+source/fastqc/0.11.4+dfsg-3
> 
> It is just over 5 years old and almost certainly lacks the updates we have been discussing:
> 
> ```
> fastqc (0.11.4+dfsg-3) unstable; urgency=medium
> 
>   * Build-Depends: libhtsjdk-java | libsam-java and try to enable
>     htsjdk.jar in Build system
> 
>  -- Andreas Tille <tille@debian.org>  Thu, 14 Jan 2016 13:50:56 +0100
> ```
> 
> I suggest you upgrade. If you would like to continue to using the Debian/Ubuntu packaging, you can try installing either the current [Ubuntu](https://launchpad.net/ubuntu/+source/fastqc/0.11.9+dfsg-4/+build/20177745/+files/fastqc_0.11.9+dfsg-4_all.deb) or [Debian](http://ftp.debian.org/debian/pool/main/f/fastqc/fastqc_0.11.9+dfsg-4_all.deb) .deb. Download the .deb and install it with `sudo dpkg --install fastqc_0.11.9+dfsg-4_all.deb`.
> 
> As an alternative (and very likely a quicker path to resolution on an older system), use the instructions here http://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc to download and install as @s-andrews has suggested.

Thank you @s-andrews and @tmancill for your comments. based on your comments, my problem was solved.
