### ISSUE TITLE
"No fonts found" when running fastqc from python 

### ISSUE THREAD

**Issue by matnguyen** [s-andrews/FastQC#7]
I can run fastqc from the command line with no issues.  However, when I try to use python's subprocess module to call fastqc through python, I get the following error: 

Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.

**Comment by s-andrews** [comment]
If FastQC runs OK from a normal command line then this must be something to do with the way you're setting up your python environment.

Given the error you've got it could be as simple as you having two different versions of java on your system and your PATH gets changed when you start the shell from within python?  Alternatively you might want to look at other variables which are set in your environment which might be getting lost.

**Comment by matnguyen** [comment]
I have checked and I only have one version of java on my system.  The PATH is the same from the command line and from Python.  Python's subprocess is supposed to inherit the current process' environment (which is the same environment where FastQC works).

**Comment by s-andrews** [comment]
Can you provide a minimal code snippet of the python you're using to call fastqc? I can try it here and at least see if it's a generic problem. Can you also post the output of:env | grep -i java..in case that shows anything interesting.On 28 May 2018 19:11, Matthew Nguyen <notifications@github.com> wrote:I have checked and I only have one version of java on my system.  The PATH is the same from the command line and from Python.  Python's subprocess is supposed to inherit the current process' environment (which is the same environment where FastQC works).

**Comment by matnguyen** [comment]
I'm calling FastQC using this function:
```python
def runCommand(self, command, directory):
     process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=directory)
     out,err = process.communicate()
     if out:
         self.logger.info("Standard output: \n" + out.decode('utf-8') + "\n")
     if err:
         self.logger.info("Standard error: \n" + err.decode('utf-8') + "\n")```

env | grep -i java gives me no output.

**Comment by matnguyen** [comment]
It turns out it was an issue with qsub/qrsh.  Thanks for your help!
