### ISSUE TITLE
ContaminantFinder is not returning best hit

### ISSUE THREAD

**Issue by jbrokamp** [s-andrews/FastQC#70]
I noticed for sequence _GATCGGAAGAGCACACGTCTGAACTCCAGTCACATT_ that I should have a **100%** match on contaminant **TruSeq Adapter, Index 27**, but `ContaminentFinder.java` returns **TruSeq Adapter, Index 8** with **96%** match. It turns out that the logic to replace the `bestHit` with `thisHit` disregards the `percentID` and only considers the sequence `length`.

@s-andrews, I'll create a pull request with a fix.

**Comment by s-andrews** [comment]
Thanks for both reporting and fixing this!  The fix will go out in the next release.
