### ISSUE TITLE
Allow user to specify more than 250 MB/thread

### ISSUE THREAD

**Issue by niemasd** [s-andrews/FastQC#75]
Currently, without editing any files, the only way to increase the amount of memory FastQC is able to use is by using multiple threads. However, we have thousands of samples we wish to run FastQC on, and we want to use 1 thread for each sample (the runtime bottlenecks of our pipeline run single-threaded only, and we don't want a multi-core AWS instance to idle). Some of our samples crash FastQC due to 250 MB being too little memory, but we don't want to use a higher-core instance type, as the instance type has plenty of RAM

As a workaround, we plan on editing the `fastqc` executable [here](https://github.com/s-andrews/FastQC/blob/b2feefa8bba752b34432e739361bdfb3804daff4/fastqc#L188) and [here](https://github.com/s-andrews/FastQC/blob/b2feefa8bba752b34432e739361bdfb3804daff4/fastqc#L192) to manually set a higher value than `250m`, but it would be great if there were a way to increase the memory allocation of FastQC without having to specify more threads.

**Comment by niemasd** [comment]
E.g. the following: https://github.com/s-andrews/FastQC/pull/76

**Comment by s-andrews** [comment]
If you're only analysing a single file then setting ```-t 2``` will only have the effect of increasing memory allocation.  The threading is done per file so it doesn't have any parallelisation effect unless you supply multiple files to analyse.

We should probably just increase the default memory allocation since there's no real reason to keep it as low as it is these days, and file sizes have grown enough that failures are getting more regular.  I'd tend to favour just increasing the default over allowing configuration since this isn't something users should need to be worrying about.

**Comment by niemasd** [comment]
That's good to know, thanks!

**Comment by xqyn** [comment]
Hi author,

Can you check the download link: https://github.com/s-andrews/FastQC/releases.
I try to download version v0.12.1  but I can only receive the v0.11.9?

**Comment by s-andrews** [comment]
The download link on github will only get you the source code.  The binaries (which is what you want if you run the program) are at https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc .  If you get the latest release then the default memory was increased anyway (I think it's 512 now?) and there is a specific command line option to increase it further if you need to.

**Comment by xqyn** [comment]
Hi, I downloaded extract from the link you sent, but it still FastQC v0.11.9 and not include to -`--memory `

**Comment by s-andrews** [comment]
I think something else must be going wrong then.  The URL I gave you links to https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip (assuming windows or linux), which is definitely the 0.12.1 version.

If you're on linux are you sure that your path is set up correctly and that you're not picking up a different installation of fastqc on the same machine?  Take a look at the install instructions in https://raw.githubusercontent.com/s-andrews/FastQC/master/INSTALL.txt particularly the part about running FastQC interactively as that contains the information about making the program executable from anywhere on your machine.

**Comment by s-andrews** [comment]
As a test, when you've installed fastqc you can run 

```
which fastqc
```

to see the location of the program you're actually running.  My guess is that this won't be where you are expecting in your case.  You can see the set of locations where your computer is looking for programs by running

```
echo $PATH
```

**Comment by xqyn** [comment]
Dear author,

Thank you so much, I make a mistake does not change the path from current (old) fastqc to new install version. many thanks for your help and my apology for any inconvenience.

**Comment by s-andrews** [comment]
> Dear author,
> 
> Thank you so much, I make a mistake does not change the path from current (old) fastqc to new install version. many thanks for your help and my apology for any inconvenience.

No problem at all.  Glad you got it working now.
