### ISSUE TITLE
Can´t install FastQC on ssh server

### ISSUE THREAD

**Issue by eibol1** [s-andrews/FastQC#79]
Hi there,

I am an beginner on informatics/bioinformatics but I really want to learn. I have some issues when I try to install FastQC on a SSH server (linux, no root privileges)

I follow the instructions and I download FastQC and unzip it:

$ `wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip` 
$ `unzip fastqc_v0.11.9.zip`
(# in the following directory: /home/abel.garcia/programs)

In Linux, I read that this is all you have to do, but then when I run `fastqc --help` I got the next error: -bash: fastqc: not found. 

Maybe I think I have to add "fastqc" to PATH or something like this?
Please if someone know something let me know how to fix this, I am stuck with that problem for some days and I don't know how to continue. If you need more information just tell me, as I said I am a beginner and don't know if this is enough.

Thank you in advance!!

**Comment by s-andrews** [comment]
You're right, that the reason this isn't working is that fastqc isn't in your PATH, but there's one other thing to fix which is to make fastqc executable.  Both of these are described in the [install.txt](https://raw.githubusercontent.com/s-andrews/FastQC/master/INSTALL.txt) document which comes with fastqc.

In your case you can get things working by running:

```
chmod 755 /home/abel.garcia/programs/FastQC/fastqc
/home/abel.garcia/programs/FastQC/fastqc --help
```
For future ease of use you will probably want to put fastqc into your PATH.  You can do this either by adding the fastqc directory to the path directly, or by putting a link to fastqc into a directory which is already in the path. So you could do either:

```
export PATH=/home/abel.garcia/programs/FastQC/:$PATH
```
..and put this into ```~/.bashrc``` so it gets rerun every time you open a new shell

..or you could do something like:

```
sudo ln -s /home/abel.garcia/programs/FastQC/fastqc /usr/local/bin/fastqc
```

In either case you can then run fastqc from anywhere on your system.

**Comment by eibol1** [comment]
Hi Andrews,

Thank you so much for the quick reply! I try what you tell me and it worked! As you said, adding fastqc into my PATH was the solution. 

Once more, thank you so much for all the support!! 👍

**Comment by s-andrews** [comment]
No problem.  Glad you're up and running.
