### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by Mikhail42** [s-andrews/FastQC#81]
I think this project need to be with high quality code. Why? Code with low quality leads to high error level. E.g., in current code there is cycle `for (int j=0;j<subFast5files.length;i++)` -- as you can see, there are 2 local variables defined in for: i and j, but i is increased. It can lead to infinite loop. With high quality code you can use, e.g, `for (File sub5Fast5File: subFast5files)`.

But before change code it is better to write tests for current code, and got around 100% code coverage.
For this purpose it is better to locate code in separated directories, according to Java projects standard: `src/main/java` and `src/test/java`. You can move files without any risk, because git support such thing and show you that only file names (file directories) was been changed.

After that, it is better to use automated tools, like Intellij Idea code inspection, to improve code quality, and prevent and fix some of bugs.

**Comment by s-andrews** [comment]
Thanks for spotting and reporting this.  I've patched that and the fix will appear in the next release.

Feel free to report any other issues you find.
