### ISSUE TITLE
Fastqc 

### ISSUE THREAD

**Issue by malar1102** [s-andrews/FastQC#83]
I'm using a m1 Mac 
ive installed fastqc using homebrew 
when I use the command which fastqc  in terminal I get. " /opt/homebrew/bin/fastqc"
I cannot run the command ./fastqc the error is zsh: permission denied: ./

I've also downloaded fastqc from the website "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/"
the fastqc I've installed does not show file option for uploading fastq files

what do I need to do to run fastqc ?

**Comment by s-andrews** [comment]
For the record this probably just meant that the fastqc launch script needed to be given execute permissions:

```chmod 755 fastqc```
