### ISSUE TITLE
No latest version

### ISSUE THREAD

**Issue by lappazos** [s-andrews/FastQC#97]
I'm deploying FastQC in my build image, and I'm searching for a link to always download the latest version, rather than specific version (e.g. wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip).
Could you please provide such an option?

**Comment by s-andrews** [comment]
I've created https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_latest.zip which will work.  I'll try to remember to update that link every time we put out a new release.

**Comment by lappazos** [comment]
Thank you, please try to remember :)
